[phases.setup]
nixPkgs = ["nodejs", "caddy"]

[phases.build]
commands = [
  "npm install --frozen-lockfile",
  "npm prune --production",
  "npm run build",
  "mv dist/restaurant-management/browser /app/dist"
]

[phases.start]
commands = ["caddy run --config /app/Caddyfile --adapter caddyfile"]
