[phases.setup]
nixPkgs = ["nodejs", "caddy"]

[phases.build]
commands = ["npm ci", "npm run build", "mv dist/restaurant-management/browser /app/dist"]

[phases.start]
commands = ["caddy run --config /app/Caddyfile --adapter caddyfile"]
