[phases.setup]
nixPkgs = ["nodejs", "caddy"]

[phases.build]
commands = ["npm install", "npm run build", "mv dist/restaurant-management/browser /app/dist"]

[phases.start]
commands = ["mkdir -p /app/dist/restaurant-management/browser && caddy run --config /app/Caddyfile --adapter caddyfile"]